### ISSUE TITLE
Ability to describe the host for software

### ISSUE THREAD

**Issue by ThetaSinner** [EphyraSoftware/Acropolis#24]
Should be possible to describe software which will run under the same process or in the same container or on the same machine.

Later it will be possible to describe grouping by network configuration but that is not part of this task.

**Comment by ThetaSinner** [comment]
Not sure how to progress this issue, if you have ideas then feel free to progress it :)

**Comment by Sub-Xaero** [comment]
I think the best conclusion we came to was that if we have entities as varied as `Docker Machine :specializes: ApplicationSoftware`, or `Server`, or `LocalMachine`, `EC2 Instance`, `Container`, which can obviously be nicely polymorphised.

Then we can make a new type of `Connectable` class, `HostedBy` which acts as a tree of sorts, with a clear `Parent > Child` relationship.

The connection type coming into being because we need to be quite generic with this, rather than just having a `Host` class with specialisations that have a OneToMany relationship with `ApplicationSoftware`, virtualisation of hardware means we have the rather interesting relationship of `Software` hosting `Software`, which can be solved quite nicely with this I think.

What do you think?

Very rough visualisation, ideally each would be its own container, but you get the gist.

![image](https://user-images.githubusercontent.com/9960703/44574203-a030b800-a780-11e8-9025-230a8f6cfe9f.png)

![image](https://user-images.githubusercontent.com/9960703/44574654-ef2b1d00-a781-11e8-949b-46045bcc7733.png)

**Comment by ThetaSinner** [comment]
Think this sounds great. Just have some implementation notes.

The problem I've already run into with polymorphism doing networks is that you can't specialize things as more than one thing. So as soon as something is connectable (system-software/application-software) it can't be hostable.

I would just put a 'hostedBy' field on the three things which can be hosted (appsoft, syssoft, datastore) then have a HostEntity which itself has a hostedBy which is also a HostEntity and you can build a hierarchy that way.

I think this will allow for a tree relationship. Because if you have a ManyToOne on the hostedBy recursion then multiple things can attach at each level.

Careful with application-software vs system-software. The distinction is documented on the entities. But it's basically just that application software is for users - a web app, a browser, excel, command shell. Everything else is software-on-software interaction. So a load balancer is system software because a user does not directly interact with it for example.

Also need to make sure that the hosting is accessible from the project. So only software is attached to the project atm, so you'd need to be able to look up hosting from the software. Which is good because it makes sense to ask 'how am I hosted'

**Comment by ThetaSinner** [comment]
Just thinking as well, there are going to be more and more places where datastores live next to system-software but must be handled separately. I think no matter the type of datastore, you can't interact with it as a user and software can't interact with it unless it's got an API of some sort. I.e. it's always going to be system-software accessible as system-software. So I think it would be great if datastore extended SystemSoftwareSpecialization and we'll worry about how to model different stores later?

**Comment by Sub-Xaero** [comment]
That all sounds solid. 

Re `ApplicationSoftware`, worth renaming to something more explicit `UserSoftware`, to distinguish it more fully. Application makes it sound more ... systemic(?) than User-y.

**Comment by ThetaSinner** [comment]
Hmm yeah. Didn't make them up, they are both well-defined on Wikipedia.
Happy to look at alternative terms as long as they are non-overlapping definitions, and also don't collide with these exiting terms :-) Anything we come up with should be easy to remember (which this clearly isn't, because 'application' is used for so many things) and all programs should fall into one category or the other with as small a grey area as possible
